{% set name = "lats" %}
{% set version = "1.0.2" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    url: https://github.com/CDAT/{{ name }}/archive/{{ version }}.tar.gz
    sha256: da8ef9a401ab943390bbf1516f27b5fe70a24e122551f7756667b4c57b54555c

build:
  number: 0
  skip: True  # [win]
 
requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
  host:
    - libnetcdf 4.*
    - hdf5 1.10.*
  run:
    - libnetcdf 4.*
    - hdf5 1.10.*

test:
  commands:
    - test -f $PREFIX/lib/liblats.a

about:
    home:  http://github.com/cdat/lats
    license: BSD-3-Clause
    license_family: BSD
    license_file: bsd-3-clause.txt
    summary: Old library to output netcdf files with some conventions

extra:
  recipe-maintainers:
     - doutriaux1
