package:
  name: vtk-cdat
  version: 7.1.0.2.10.1

source:
  git_rev: 1c03d1d03b1c12d99dd090ba4c5ca078e2d9612f
  git_url: git://github.com/Kitware/VTK.git

build:
  number: 0
  detect_binary_files_with_prefix: true
  has_prefix_files:                           [win]
    - Lib/site-packages/vtk/__init__.py       [win]

requirements:
  build:
    - cmake
    - python
    - proj4 >4.9.2
    - hdf5 1.8.18
    - ffmpeg
    - freetype
    - x264 <20151006.2245
    - gcc [linux]
    - libgcc [linux]
  run:
    - python
    - proj4 >4.9.2
    - hdf5 1.8.18
    - ffmpeg
    - freetype
    - x264 <20151006.2245
    - gcc [linux]
    - libgcc [linux]

about:
  home: http://www.vtk.org/
  license: BSD
  summary: VTK is an open-source, freely available software system for 3D computer graphics

extra:
  recipe-maintainers:
    - doutriaux1
    - sankhesh
    - danlipsa
