{% set version = "2.10" %}
{% set name = "vtk-cdat" %}

package:
    name: {{ name }}
    version: 7.1.0.{{ version }}

source:
    git_rev: 1c03d1d03b1c12d99dd090ba4c5ca078e2d9612f
    git_url: git://github.com/Kitware/VTK.git

build:
    skip: True  # [win or py3k]
    number: 0
    detect_binary_files_with_prefix: true
    has_prefix_files:                           [win]
        - Lib/site-packages/vtk/__init__.py       [win]

requirements:
    build:
        - cmake
        - python
        - proj4 >4.9.2
        - hdf5 1.8.18
        - ffmpeg
        - freetype
        - x264 <20151006.2245
        - gcc  # [linux]
        - libgcc  # [linux]
        - toolchain
    run:
        - python
        - proj4 >4.9.2
        - hdf5 1.8.18
        - ffmpeg
        - freetype
        - x264 <20151006.2245
        - gcc  # [linux]
        - libgcc  # [linux]

test:
    imports:
        - vtk
        - vtk.vtkCommonCore

about:
    home: http://www.vtk.org/
    license: BSD 3-Clause
    license_file: Copyright.txt
    summary: >
        The Visualization Toolkit (VTK) is an open-source, freely available software
        system for 3D computer graphics, modeling, image processing, volume 
        rendering, scientific visualization, and information visualization.

extra:
    recipe-maintainers:
        - doutriaux1
        - sankhesh
        - danlipsa
