{% set version = "7.1.0.2.10" %}
{% set name = "vtk-cdat" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    git_rev: 1c03d1d03b1c12d99dd090ba4c5ca078e2d9612f
    git_url: git://github.com/Kitware/VTK.git

build:
    skip: True  # [win or py3k]
    number: 0
    detect_binary_files_with_prefix: true

requirements:
  build:
    - toolchain
    - cmake
    - ninja
    - python
    # VTK Third Party dependencies
    - zlib 1.2.*
    - freetype 2.7.*
    - hdf5 1.8.18|1.8.18.*  # [unix]
    - libxml2 2.9.*
    - libpng >=1.6.23,<1.7
    - jpeg 9*
    - libtiff 4.0.*
    - jsoncpp  # [unix]
    - expat
	- proj4 4.9.3
	- ffmpeg
	- x264 20131217
  run:
    - python
    - future  # used in the generated python wrappers
    # VTK Third Party dependencies
    - zlib 1.2.*
    - freetype 2.7.*
    - hdf5 1.8.18|1.8.18.*  # [unix]
    - libxml2 2.9.*
    - libpng >=1.6.23,<1.7
    - jpeg 9*
    - libtiff 4.0.*
    - jsoncpp  # [unix]
    - expat
	- proj4 4.9.3
	- ffmpeg
	- x264 20131217
	- toolchain

test:
    imports:
        - vtk
        - vtk.vtkCommonCore

about:
    home: http://www.vtk.org/
    license: BSD 3-Clause
    license_file: Copyright.txt
    summary: >
        The Visualization Toolkit (VTK) is an open-source, freely available software
        system for 3D computer graphics, modeling, image processing, volume 
        rendering, scientific visualization, and information visualization.

extra:
    recipe-maintainers:
        - doutriaux1
        - sankhesh
        - danlipsa
